### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sjvrijn**
I've updated the `CONTRIBUTING.md` file to match the agreed procedure in [this discussion](https://github.com/orgs/SS-NES/discussions/4)

### CODE REVIEW

**Comment by neutvd** [comment]
@c-martinez For now a rough draft of the Continuous Integration and Continuous Delivery episode. I would appreciate it if you could give it a quick review to confirm I am on the right track.

**Comment by c-martinez** [comment]
I'm guessing that I should be reviewing https://github.com/SS-NES/SS-NES-lesson/pull/6 more than this PR, is that right @neutvd?

**Comment by neutvd** [comment]
> I'm guessing that I should be reviewing #6 more than this PR, is that right @neutvd?

Yes, I have no idea how my comment ended up here. I thought it was a comment on my own PR. My apologies, have to get used to the github UI I think. Thank you for your comments, I have already started working on them, but nothing pushed to the PR yet.

**Comment by c-martinez** [comment]
No worries -- please tag me again if you want me to have another look :-)

**Review by GiulioRosani — APPROVED** [review]
Looks good. Nothing to add.

**Pull request merged**
